"""Available versions of "chromium".

DO NOT EDIT. Generated by //browsers/private/update-tool:update-tool.
"""

DEFAULT_VERSION = "143.0.7459.0"

VERSIONS = {
    "128.0.6613.137": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "ab945ee7dd4a86ff0eed01f48ef712e159066e9690259cbf275040f575c6cccd",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "42bb91660a3c5d31cbc06eab5080afb2d631f759de711f09a069a17a9f4a86a2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "8a230d16b93ae37aaf48d13abf7367b21b057a29bdedfbfd544cc19adc59b1fa",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/win64/chrome-headless-shell-win64.zip",
            "integrity": "60c7148e42fa36085c4903f91c06cbeba99a3a56c2f6f479b8f4b5508ca20297",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "129.0.6668.100": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "2525e51e13fac1106e3d86e8a591d69341232b881b17f781803520afd89e178c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "179ab4d0712c9328920e6531c7cf01a862855160d1164de3ef6fd52cd533848e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "37354477a36d6110642351633fee27dd0d45c689f4a2034d7a1455896da1eae9",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/win64/chrome-headless-shell-win64.zip",
            "integrity": "29e8c023ba63ec47debbdd359d977ab70414a2c168506ebce9936313bd1f022a",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "130.0.6723.116": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "686efe6dcfba3741d822adecb31da561d7be9fa8a0ff32cf260ff287380ad3a5",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "9ba7ec2c2a5cdf6025c50719ad96119f73f6a39f2513eb957eaa3568de01863e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "91f0c30299bfb422a3a40f3f043111e928b37c75f7befbaf137a39faff82f8cb",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/win64/chrome-headless-shell-win64.zip",
            "integrity": "8f381cb17452daff6b9c15b3152f1e3e696a366c697e32fd67db3a05a5d87ab6",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "131.0.6778.264": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "9a8014dbdc8a35e76949ccdfa2c13fafb93d2cc234bbee2cc40312d97328fd0f",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "15cc329db4b7151373954c08d500480c0215ab7a04fa098d6daa6374d5516589",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "eb1a3f5a4119a72630b9454ad86cbad29f0a5af0749ad8955077e49e43dbbd1b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/win64/chrome-headless-shell-win64.zip",
            "integrity": "83720edec5a520fd4b7592c0f004c850480368f89501a6ab26da5b1942e67e9c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "132.0.6834.159": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "1dd8c80b22b7c04a5339f7c4ca1b08ce2e8841c35aa1a6d1d3927d552dcbe900",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "ad7a3246326ea08bf9930bc175d97781014367382fb2fe69cc84c4abd60e442e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "fbf7b62161984cb42d1c80fc226b8e1106711c6970be62f1d4c1a5d073cbc743",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/win64/chrome-headless-shell-win64.zip",
            "integrity": "3e7a9cc5b55ed4731b602db66b27368aa87f3e68df649b7129af29a306573248",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "133.0.6943.141": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "cec67d7e4baf84814a8602ea59aa07a669f31d95e63e935b5e7b39e5986895a2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "b7a12980ae2e0563f0d36119a078aec2e78d0fdc8c4b14f02be24c58a027d3f8",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "18c395d2d4e469c713e55f2d362ad5a46b8629885bd2a69576010f95bf95d3ae",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/win64/chrome-headless-shell-win64.zip",
            "integrity": "16a32d2c61754705ad73cb6d920e19198562cf9c58fe4723df2812c244beca13",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "134.0.6998.165": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "cda318dcbf2cccb89ce48dc4a65add41510323972c829b7df18a6acbaf0de573",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "e285ed8f82c97b3759e509c166e3ff54e5a868356db8315874954d25cb3fff4d",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "f486978f6d20f19d7071c6367933864a553174b8a5c22a5b7f195d8b73cb9fdd",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/win64/chrome-headless-shell-win64.zip",
            "integrity": "cc5dfbe337724e6141586a9a5ef76028f1bd1192d67c65471e5a79cd1afd0374",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "135.0.7049.114": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "edc2f6118c68f3c369f0dde3c2c31e400806308ab02ba3e2901e742212246e2e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "d11d798ee9d88e58e472dde5848e9766bd9334520b93cc76d4a657a8c5e09394",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "8d5e637de58362ecd260587e986419c7dc19a5dfebf1900611313a7f70169a5e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/win64/chrome-headless-shell-win64.zip",
            "integrity": "cd2d3906c8029e4c0b0f74376d78750e961f2a4b4a4a85c6cd9ead6b0858b5df",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "136.0.7103.113": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "484778f66466a0d179d16e3e2de66e4efbcd3b24bed0d2fc0864f43d68d46efa",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "8d1c97da2c20a774d2f13f0b8ae3446ef73c4a2d5c59caebdf2568192d127fb7",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "59215e859f0f665518273cc72f9ff293ef948d11021e9adef9aa6166bf0b3ccf",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/win64/chrome-headless-shell-win64.zip",
            "integrity": "5891697b505ee2c732c984d648291aeb296826a0315a6a36a6928309936dda70",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "137.0.7151.119": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "9dc00173ad9d156ada860b51fb4f91abe5563e7ebb84bb09c237e44f5f741c91",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "530489da62d26e89de598b6971fd34d45c1b9a0b02f65d09bdfe251ed9f20811",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "bb970ac1288c9141fa362daffcd0f49c82613d2f2ed4deafd792f30750192b94",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/win64/chrome-headless-shell-win64.zip",
            "integrity": "f04d4655ea38b0eb26e770eadfa3a330694e3468e4753e107a94e0ccdb6c8458",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "138.0.7204.183": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "0b255a51ec03b8762da532741c10a2d858a8ecf7dc26a57a1bb137f50551845b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "4c54c6187023692f0a8db1aa4a42496f6c0396464f46e00962f5c16ccc194c46",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "3af5c746bbd157c878986535b80760f62dd05199e15be938aa71b88cab803d30",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/win64/chrome-headless-shell-win64.zip",
            "integrity": "560b2829a691e3299ae11787dd22b9a5aca032667f50fc455c4b7b4e6f3916ae",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "139.0.7258.154": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "8551dcb89673980616528b0af3697623930bec62efb06014a54cd961a7199497",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "4eab0a528bfc0a00b9935eb8a37c5154705146392060e7a44c744f16c293ba7f",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "b0bafb0c23996ced6994e7eb327c881ea0d4f4803424246ce7cef70dfef0cc56",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/win64/chrome-headless-shell-win64.zip",
            "integrity": "143ac74e6dba022ecfebeff70ad399060ffec0348d93adc5c31d9e4020ab702c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "140.0.7339.207": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "39fcb6acdf442e5560bc3cdd6ec0a7b3174998a9761f391c156a4d26df5a0b19",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "df4545512e527b29149f9166015a1ca3e2a743816325264fec9f18fd54f355e2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "0418c337d53a12dc0908527fcd0478a135497a147a33ae6a39113a16c64fe9f3",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/win64/chrome-headless-shell-win64.zip",
            "integrity": "6fb1836cad8148016fa28df1a77baa1d77aaadf04e483fbeb12c73e8184bad90",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "141.0.7390.54": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "cba167189d1e676a10bb0a1d52b43a26eb7d6c15dd6f05ae76cff100c30d547a",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "7f7ab9a831391fa7d183b08fcf90ba6bcd5023e0663efd335faec40ece3eb749",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "6a0b3f4f13adf89f5fd8618ba68ef9ef0ab375e4f53fad4d5d56cf801054b7f2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/win64/chrome-headless-shell-win64.zip",
            "integrity": "1264ee192ca001359b4527d195d635c4f33312543a90e31359bac38931d34f81",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "142.0.7444.6": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "155fe3738dc90b9723752974eb93a0500de631fe5de0732be1a79d00ff565962",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "16882cc7cb5b86d491ecd9669c9d9a3b2c591f9ac031774476cf4f99c254b579",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "ad608b5afff4dec60778ed83fab4f0d6b8563ab7ac94b3b48b1e0cebabec392e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/win64/chrome-headless-shell-win64.zip",
            "integrity": "f3d396ad4b6244feee263a6b39d8e8b32f1d568db74a333c2e7679e0fcd7ab09",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "141.0.7390.65": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "74d44ced303a896494cfae337bce4996bf81f2941e302784068d4699b4501415",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "f0ca463bc331c86e15db1cdc32f847d632a1a8d34e6e8d8a24cb2564131a7c08",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "8d30ea656885698e0126c25b0ea27d946a9ae7a0349bf1ef2cd9ebb5ac1a4ac1",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/win64/chrome-headless-shell-win64.zip",
            "integrity": "2634b1a2d2893de6472d8be5ca74fee31c2a10c1d2a68d8f7a06fb08a970c3cf",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "143.0.7459.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "79a3a4d3a5f9efae04dbb7c2164393ff8fee5f352ec73e36900848c75f4f906f",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "cdba96e69a423adc1f2647f35643a10e33260b4dfcc233977f3724f28bffd8f2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "56eb0c57958b50dc6c0de810ea9fcf1ff800baf2a4b14ae0fea536e633806098",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/win64/chrome-headless-shell-win64.zip",
            "integrity": "506b23250323f3eb4cdfe298cfd599571e428f6f3a64e86818ee975f4e585b75",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
}
